services:
  c_slaw_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=emre12321
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/slaw.pfx
    ports:
      - 7251:8080
      - 7252:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro