services:
  c_slaw_api:
    image: slaw-api
    build:
      context: .
      dockerfile: Presentation/SLaw.API/Dockerfile
    networks:
      slaw_network:
        ipv4_address: 172.20.2.5
    depends_on:
        - s_postgres
  c_slaw_client:
    image: slaw-client
    build:
      context: Presentation/slaw.client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/etc/positivessl/live/seshukuk/:/etc/positivessl/live/seshukuk:ro
    networks:
      slaw_network:
        ipv4_address: 172.20.2.2
  s_postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emre12321
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /appdata/postgres:/var/lib/postgresql/data
    networks:
      slaw_network:
        ipv4_address: 172.20.2.3
  s_pgAdmin4:
    image: dpage/pgadmin4
    container_name: c_pgAdmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=emreyildizcr@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=emre12321
    user: '$UID:$GID'
    volumes:
      - /appdata/pgAdmin4:/var/lib/pgadmin
    networks:
      slaw_network:
        ipv4_address: 172.20.2.4
networks:
  slaw_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24